---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat"

- name: Add Zabbix YUM repo
  yum_repository:
    name: zabbix
    description: Official Zabbix {{ zabbix_web_major_version }} YUM repo
    baseurl: "{{ zabbix_web_yumrepo_url }}"
    gpgcheck: no
    params: "{{ zabbix_web_yumrepo_params }}"
  tags:
    - zabbix_web_pkg

- name: Intall Zabbix web
  package:
    name: "{{ zabbix_web_pkg }}"
  notify:
    - Restart web server daemon
  tags:
    - zabbix_web_pkg

- name: Change permissions on the session directory
  file:
    path: "{{ zabbix_web_php_session_dir }}"
    group: apache
    mode: 0775
  when: >
    zabbix_web_php_session_dir is not none and
    zabbix_web_major_version | int >= 3 and
    ansible_distribution_major_version | int < 7
  tags:
    - zabbix_web_pkg

- name: Configure Zabbix web
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    group: apache
    mode: 0640
  notify:
    - Restart web server daemon
  tags:
    - zabbix_web_config

- name: Configure Zabbix maintenance mode
  template:
    src: maintenance.inc.php.j2
    dest: /etc/zabbix/web/maintenance.int.php
  when: zabbix_web_maintenance_mode
  notify:
    - Restart web server daemon
  tags:
    - zabbix_web_config

- name: Add the web server user into an extra group
  user:
    name: "{{ zabbix_web_server_user }}"
    groups: "{{ zabbix_web_server_group }}"
  when: >
    zabbix_web_server_user is not none and
    zabbix_web_server_group is not none
  notify:
    - Restart web server daemon
  tags:
    - zabbix_web_user
